# Generated by Django 4.1.1 on 2022-09-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="medicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Nombre del medicamento"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=250, verbose_name="Descripcion del medicamento"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Precio"
                    ),
                ),
                ("stock", models.PositiveIntegerField(verbose_name="Cantidad")),
            ],
        ),
    ]
