# Generated by Django 4.1.1 on 2022-09-13 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pastillas", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="medicine",
            options={
                "verbose_name": "Medicamento",
                "verbose_name_plural": "Medicamentos",
            },
        ),
        migrations.AlterUniqueTogether(
            name="medicine",
            unique_together={("name", "description", "price", "stock")},
        ),
    ]
