# Generated by Django 4.1.1 on 2022-09-16 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pastillas", "0002_alter_medicine_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicine",
            name="name",
            field=models.CharField(
                max_length=200, unique=True, verbose_name="Nombre del medicamento"
            ),
        ),
    ]
