# Generated by Django 4.1.1 on 2022-09-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nombre")),
                ("cedule", models.CharField(max_length=10, verbose_name="Cedula")),
                ("phone", models.CharField(max_length=10, verbose_name="Telefono")),
                (
                    "direction",
                    models.CharField(max_length=250, verbose_name="Direccion"),
                ),
            ],
            options={
                "verbose_name": ("Doctor",),
                "verbose_name_plural": ("Doctores",),
            },
        ),
    ]
