# Generated by Django 4.1.1 on 2022-09-13 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pastillas", "0002_alter_medicine_options_and_more"),
        ("doctors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportDoctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "patient_name",
                    models.CharField(max_length=250, verbose_name="Nombre Paciente"),
                ),
                (
                    "patient_Cedule",
                    models.CharField(max_length=250, verbose_name="Cedula"),
                ),
                (
                    "patient_phone",
                    models.CharField(max_length=250, verbose_name="Telefono"),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="doctors.doctors",
                        verbose_name="Medico",
                    ),
                ),
                (
                    "medicament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pastillas.medicine",
                        verbose_name="Pastillas",
                    ),
                ),
            ],
            options={
                "verbose_name": ("Reporte",),
                "verbose_name_plural": ("Reportes",),
            },
        ),
    ]
