# Generated by Django 4.1.1 on 2022-09-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0002_reportdoctor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctors",
            name="cedule",
            field=models.CharField(max_length=10, unique=True, verbose_name="Cedula"),
        ),
        migrations.AlterField(
            model_name="doctors",
            name="name",
            field=models.CharField(max_length=200, unique=True, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="doctors",
            name="phone",
            field=models.CharField(max_length=10, unique=True, verbose_name="Telefono"),
        ),
    ]
