# Generated by Django 4.1.1 on 2022-09-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0003_alter_doctors_cedule_alter_doctors_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportdoctor",
            name="patient_Cedule",
            field=models.CharField(max_length=10, verbose_name="Cedula"),
        ),
        migrations.AlterField(
            model_name="reportdoctor",
            name="patient_phone",
            field=models.CharField(max_length=10, verbose_name="Telefono"),
        ),
    ]
